ARG POETRY_VERSION=1.1.13
ARG PYTHON_VERSION

FROM mwalbeck/python-poetry:${POETRY_VERSION}-${PYTHON_VERSION}

ARG WORKDIR=/__w/bearboto3/bearboto3
WORKDIR ${WORKDIR}

ENV PIP_DISABLE_PIP_VERSION_CHECK=1

ENV POETRY_VIRTUALENVS_CREATE=false

RUN apt update && \
    apt install \
    --no-install-recommends \
    -y \
    git && \
    apt-get clean