[tool.poetry]
name = "beartype-boto3"
version = "0.1.0"
description = ""
authors = ["Paul <dev@studiop.page>"]

[tool.poetry.dependencies]
python = "^3.8"
beartype = "^0.9.1"
boto3 = "^1.20.4"
boto3-stubs = {extras = ["s3"], version = "^1.20.4"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
