[tool.poetry]
name = "bearboto3"
version = "0.1.0"
description = ""
authors = ["Paul <dev@studiop.page>"]

[tool.poetry.dependencies]
python = "^3.6.7"
beartype = "^0.9.1"
boto3-stubs = {extras = ["all"], version = "^1.20.5"}

[tool.poetry.dev-dependencies]
pylint = "^2.11.1"
pytest = "^6.2.5"
black = "^21.10b0"
boto3 = "^1.20.5"
moto = {extras = ["all"], version = "^2.2.14"}


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.messages_control]
max-line-size = 120

disable = [
    "missing-module-docstring",
    "missing-function-docstring"
]

[tool.black]
line-length = 120
