name: Build
on:
  push:
    branches-ignore:
      - main
    paths:
      - Dockerfile
      - Dockerfile.base
      - poetry.lock
      - .github/workflows/docker.yml
      - .github/workflows/build.yml
  workflow_dispatch:

concurrency: 
  group: ${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build-base:
    uses: ./.github/workflows/docker.yml
    with:
      dockerfile: Dockerfile.base
      image-name: bearboto3-base

  build-project:
    needs: build-base
    uses: ./.github/workflows/docker.yml
    with:
      dockerfile: Dockerfile
      image-name: bearboto3
      pyproject-path: .

  build-integration:
    needs: build-base
    uses: ./.github/workflows/docker.yml
    with:
      dockerfile: Dockerfile
      image-name: bearboto3-int
      pyproject-path: integration
