name: Build
on:
  push:
    branches-ignore:
      - main
    paths:
      - Dockerfile
      - Dockerfile.base
      - poetry.lock
  workflow_dispatch:

jobs:
  build-base:
    uses: ./.github/workflows/docker.yml
    with:
      dockerfile: Dockerfile.base
      image-name: bearboto3-base

  build-project:
    needs: build-base
    uses: ./.github/workflows/docker.yml
    with:
      dockerfile: Dockerfile
      image-name: bearboto3
      pyproject-path: pyproject.toml

  build-integration:
    needs: build-base
    uses: ./.github/workflows/docker.yml
    with:
      dockerfile: Dockerfile
      image-name: bearboto3-int
      pyproject-path: integration/pyproject.toml
