name: Integration
on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  integration:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - '3.10'
        beartype-version:
          - 0.9
          - '0.10'
        stubs:
          - ''
          - '[s3,ec2]'
    runs-on: ubuntu-latest
    container: ghcr.io/beartype/bearboto3-int:${{ matrix.python-version }}
    defaults:
      run:
        working-directory: integration
    steps:
        # Checkout always clones to $GITHUB_WORKSPACE so not affected by workdir setting
      - name: Clone repo
        uses: actions/checkout@v3

        # WORKDIR takes affect starting here
      - name: Install beartype ${{ matrix.beartype-version }}
        run: poetry add beartype@^${{ matrix.beartype-version }}

      - name: Install bearboto3 (and optionally install stub extras)
        run: poetry add git+https://github.com/beartype/bearboto3#main${{ matrix.stubs }}

      - name: Run integration project
        run: python3 integration.py