name: Integration
on:
  push:
    tags:
      - '*'

env:
  POETRY_VERSION: 1.1.12

jobs:
  integration:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: $POETRY_VERSION

      - name: Install integration project
        run: poetry install

      - name: Run integration
        run: poetry run python3 integration.py