name: Scratch
on:
  push:
  workflow_dispatch:

jobs:
  scratch:
    runs-on: ubuntu-latest
    container:
      image: alpine
    defaults:
      run:
        working-directory: /
    steps:
      - run: echo $GITHUB_WORKSPACE
      - run: pwd
      - run: ls -la
      - run: cat /etc/os-release